import type { CanvasElement,Page } from "@giraffle/domain";
import { invalid } from "./errors";

export type CanvasLayout="preserve"|"grid"|"horizontal"|"vertical"|"mindmap"|"radial"|"timeline"|"columns";
export type CanvasNodeStyle="default"|"primary"|"accent"|"muted"|"note";
export interface CanvasSpecNode{key:string;text:string;pageId?:string|null;style?:CanvasNodeStyle;x?:number;y?:number;width?:number;height?:number}
export interface CanvasSpecEdge{key?:string;from:string;to:string;label?:string|null}
export interface CanvasSpec{layout?:CanvasLayout;nodes:CanvasSpecNode[];edges?:CanvasSpecEdge[]}
export interface CanvasApplyResult{elements:CanvasElement[];created:number;updated:number;deleted:number;unchanged:number;managedNodes:number;managedEdges:number}

type Json=Record<string,unknown>;
interface GraphNode extends CanvasSpecNode{x:number;y:number;width:number;height:number}
interface GraphEdge{key:string;from:string;to:string;label:string|null}
interface Graph{nodes:Map<string,GraphNode>;edges:Map<string,GraphEdge>}
interface ManagedData{giraffleManagedKey?:unknown;giraffleManagedKind?:unknown;giraffleManagedPart?:unknown;giraffleManagedText?:unknown;giraffleManagedStyle?:unknown;giraffleManagedFrom?:unknown;giraffleManagedTo?:unknown;giraffleManagedLabel?:unknown;girafflePageId?:unknown}

const palettes:Record<CanvasNodeStyle,{background:string;stroke:string;text:string}>={
  default:{background:"#edf4ff",stroke:"#1f2937",text:"#0f172a"},
  primary:{background:"#dbeafe",stroke:"#2563eb",text:"#172554"},
  accent:{background:"#fef3c7",stroke:"#d97706",text:"#451a03"},
  muted:{background:"#f1f5f9",stroke:"#94a3b8",text:"#334155"},
  note:{background:"#fef9c3",stroke:"#ca8a04",text:"#422006"},
};
const gapX=100,gapY=64;
const finite=(value:unknown,fallback:number)=>typeof value==="number"&&Number.isFinite(value)?value:fallback;
const positive=(value:unknown,fallback:number)=>Math.max(40,finite(value,fallback));
function data(element:CanvasElement):ManagedData{return(element.customData??{}) as ManagedData;}
function textSize(text:string,width?:number,height?:number){const lines=text.split("\n");const longest=Math.max(1,...lines.map((line)=>line.length));return{width:positive(width,Math.min(360,Math.max(140,longest*8.5+40))),height:positive(height,Math.max(72,lines.length*25+32))};}
function edgeKey(edge:CanvasSpecEdge){return edge.key?.trim()||`${edge.from}->${edge.to}`;}
function hash(value:string){let first=2166136261,second=0x9e3779b9;for(let i=0;i<value.length;i++){const code=value.charCodeAt(i);first=Math.imul(first^code,16777619);second=Math.imul(second+code+(second<<6)+(second>>>2),2246822519);}return`${(first>>>0).toString(36)}${(second>>>0).toString(36)}`;}
function elementId(canvasId:string,key:string,part:string){return`gg-${part}-${hash(`${canvasId}\0${key}\0${part}`)}`;}
function nonce(id:string){return Number.parseInt(hash(id).slice(0,8),36)%2_000_000_000;}
function base(id:string,type:string,x:number,y:number,width:number,height:number,index:number):Json{return{id,type,x,y,width,height,angle:0,strokeColor:"#1f2937",backgroundColor:"transparent",fillStyle:"solid",strokeWidth:2,strokeStyle:"solid",roughness:1,opacity:100,groupIds:[],frameId:null,index:`a${index.toString(36)}`,roundness:type==="rectangle"?{type:3}:null,seed:nonce(`${id}:seed`),version:1,versionNonce:nonce(id),isDeleted:false,boundElements:[],updated:Date.now(),link:null,locked:false};}
function managed(key:string,kind:string,part:string,extra:Json={}):Json{return{giraffleManagedKey:key,giraffleManagedKind:kind,giraffleManagedPart:part,...extra};}

function graphFrom(elements:readonly CanvasElement[]):Graph{const graph:Graph={nodes:new Map(),edges:new Map()};for(const element of elements){if(element.isDeleted)continue;const custom=data(element);const key=typeof custom.giraffleManagedKey==="string"?custom.giraffleManagedKey:null;if(!key)continue;if(custom.giraffleManagedKind==="node"&&custom.giraffleManagedPart==="shape"){const text=typeof custom.giraffleManagedText==="string"?custom.giraffleManagedText:key;const size=textSize(text,element.width as number,element.height as number);graph.nodes.set(key,{key,text,pageId:typeof custom.girafflePageId==="string"?custom.girafflePageId:null,style:isStyle(custom.giraffleManagedStyle)?custom.giraffleManagedStyle:"default",x:finite(element.x,0),y:finite(element.y,0),...size});}else if(custom.giraffleManagedKind==="edge"&&custom.giraffleManagedPart==="line"){const from=typeof custom.giraffleManagedFrom==="string"?custom.giraffleManagedFrom:null,to=typeof custom.giraffleManagedTo==="string"?custom.giraffleManagedTo:null;if(from&&to)graph.edges.set(key,{key,from,to,label:typeof custom.giraffleManagedLabel==="string"?custom.giraffleManagedLabel:null});}}return graph;}
function isStyle(value:unknown):value is CanvasNodeStyle{return typeof value==="string"&&value in palettes;}
function addSpec(graph:Graph,spec:CanvasSpec,pages:ReadonlyMap<string,Page>){const seen=new Set<string>();for(const item of spec.nodes){const key=item.key.trim();if(!key||seen.has(key))invalid(`Canvas node key must be unique: ${item.key}`);seen.add(key);if(item.pageId&&!pages.has(item.pageId))invalid(`Page not found: ${item.pageId}`);const current=graph.nodes.get(key);const size=textSize(item.text,item.width??current?.width,item.height??current?.height);graph.nodes.set(key,{key,text:item.text,pageId:item.pageId===undefined?current?.pageId??null:item.pageId,style:item.style??current?.style??"default",x:finite(item.x,current?.x??0),y:finite(item.y,current?.y??0),...size});}
for(const item of spec.edges??[]){const key=edgeKey(item);if(!graph.nodes.has(item.from)||!graph.nodes.has(item.to))invalid(`Canvas edge ${key} refers to a missing node`);graph.edges.set(key,{key,from:item.from,to:item.to,label:item.label??null});}}
function layoutGraph(graph:Graph,mode:CanvasLayout){if(mode==="preserve")return;const nodes=[...graph.nodes.values()];if(!nodes.length)return;const place=(node:GraphNode,x:number,y:number)=>{node.x=Math.round(x);node.y=Math.round(y);};
if(mode==="horizontal"||mode==="timeline"){let x=40;nodes.forEach((node,index)=>{place(node,x,mode==="timeline"?80+(index%2)*180:80);x+=node.width+gapX;});return;}
if(mode==="vertical"){let y=40;nodes.forEach((node)=>{place(node,80,y);y+=node.height+gapY;});return;}
if(mode==="radial"){place(nodes[0]!,360,280);const rest=nodes.slice(1),radius=Math.max(260,rest.length*48);rest.forEach((node,index)=>{const angle=(Math.PI*2*index)/Math.max(1,rest.length)-Math.PI/2;place(node,440+Math.cos(angle)*radius-node.width/2,320+Math.sin(angle)*radius-node.height/2);});return;}
if(mode==="mindmap"){const indegree=new Map(nodes.map((node)=>[node.key,0]));for(const edge of graph.edges.values())indegree.set(edge.to,(indegree.get(edge.to)??0)+1);let frontier=nodes.filter((node)=>(indegree.get(node.key)??0)===0).map((node)=>node.key);if(!frontier.length)frontier=[nodes[0]!.key];const levels=new Map<string,number>(),queue=frontier.map((key)=>({key,level:0}));while(queue.length){const item=queue.shift()!;if(levels.has(item.key))continue;levels.set(item.key,item.level);for(const edge of graph.edges.values())if(edge.from===item.key)queue.push({key:edge.to,level:item.level+1});}for(const node of nodes)if(!levels.has(node.key))levels.set(node.key,0);const grouped=new Map<number,GraphNode[]>();for(const node of nodes){const level=levels.get(node.key)??0;grouped.set(level,[...(grouped.get(level)??[]),node]);}for(const[level,items]of grouped){const total=items.reduce((sum,node)=>sum+node.height,0)+gapY*(items.length-1);let y=360-total/2;for(const node of items){place(node,60+level*340,y);y+=node.height+gapY;}}return;}
const columns=mode==="columns"?3:Math.max(1,Math.ceil(Math.sqrt(nodes.length)));const widths=Array(columns).fill(0) as number[];nodes.forEach((node,index)=>{const column=index%columns;widths[column]=Math.max(widths[column]??0,node.width);});const xs:number[]=[];let x=40;for(const width of widths){xs.push(x);x+=width+gapX;}const ys=Array(columns).fill(40) as number[];nodes.forEach((node,index)=>{const column=index%columns;place(node,xs[column]??40,ys[column]??40);ys[column]=(ys[column]??40)+node.height+gapY;});}
function boundary(node:GraphNode,target:GraphNode){const cx=node.x+node.width/2,cy=node.y+node.height/2,tx=target.x+target.width/2,ty=target.y+target.height/2,dx=tx-cx,dy=ty-cy;if(!dx&&!dy)return{x:cx,y:cy};const scale=Math.min(Math.abs((node.width/2)/dx)||Infinity,Math.abs((node.height/2)/dy)||Infinity);return{x:cx+dx*scale,y:cy+dy*scale};}
function compile(canvasId:string,graph:Graph){const elements:CanvasElement[]=[],nodeShapes=new Map<string,Json>();let index=0;for(const node of graph.nodes.values()){const shapeId=elementId(canvasId,node.key,"node"),textId=elementId(canvasId,node.key,"text"),palette=palettes[node.style??"default"];const shape={...base(shapeId,"rectangle",node.x,node.y,node.width,node.height,index++),strokeColor:palette.stroke,backgroundColor:palette.background,boundElements:[{type:"text",id:textId}],link:node.pageId?`https://giraffle.local/page/${encodeURIComponent(node.pageId)}`:null,customData:managed(node.key,"node","shape",{giraffleManagedText:node.text,giraffleManagedStyle:node.style??"default",...(node.pageId?{girafflePageId:node.pageId}:{})})};const fontSize=20,lineHeight=1.25,textHeight=Math.max(25,node.text.split("\n").length*fontSize*lineHeight);const label={...base(textId,"text",node.x+16,node.y+(node.height-textHeight)/2,node.width-32,textHeight,index++),strokeColor:palette.text,backgroundColor:"transparent",fillStyle:"solid",strokeWidth:1,roughness:0,roundness:null,boundElements:null,text:node.text,fontSize,fontFamily:5,textAlign:"center",verticalAlign:"middle",containerId:shapeId,originalText:node.text,autoResize:true,lineHeight,customData:managed(node.key,"label","text")};nodeShapes.set(node.key,shape);elements.push(shape as unknown as CanvasElement,label as unknown as CanvasElement);}
for(const edge of graph.edges.values()){const from=graph.nodes.get(edge.from),to=graph.nodes.get(edge.to);if(!from||!to)continue;const start=boundary(from,to),end=boundary(to,from),id=elementId(canvasId,edge.key,"edge");const line={...base(id,"arrow",start.x,start.y,Math.abs(end.x-start.x),Math.abs(end.y-start.y),index++),roundness:{type:2},points:[[0,0],[end.x-start.x,end.y-start.y]],lastCommittedPoint:null,startBinding:{elementId:elementId(canvasId,from.key,"node"),focus:0,gap:8},endBinding:{elementId:elementId(canvasId,to.key,"node"),focus:0,gap:8},startArrowhead:null,endArrowhead:"arrow",customData:managed(edge.key,"edge","line",{giraffleManagedFrom:edge.from,giraffleManagedTo:edge.to,...(edge.label?{giraffleManagedLabel:edge.label}:{})})};for(const key of [from.key,to.key]){const shape=nodeShapes.get(key);if(shape)(shape.boundElements as Json[]).push({type:"arrow",id});}elements.push(line as unknown as CanvasElement);if(edge.label){const labelId=elementId(canvasId,edge.key,"edge-label"),fontSize=16,width=Math.max(70,edge.label.length*8+20),height=28;elements.push({...base(labelId,"text",(start.x+end.x-width)/2,(start.y+end.y-height)/2,width,height,index++),strokeColor:"#475569",backgroundColor:"#ffffff",roughness:0,roundness:null,boundElements:null,text:edge.label,fontSize,fontFamily:5,textAlign:"center",verticalAlign:"middle",containerId:null,originalText:edge.label,autoResize:true,lineHeight:1.25,customData:managed(edge.key,"edge-label","text")} as unknown as CanvasElement);}}
return elements;}
function comparable(element:CanvasElement){const{version:_version,versionNonce:_nonce,updated:_updated,...rest}=element;return JSON.stringify(rest);}
function reconcile(existing:readonly CanvasElement[],desired:readonly CanvasElement[]):CanvasApplyResult{const current=new Map(existing.map((element)=>[element.id,element])),wanted=new Set(desired.map((element)=>element.id));let created=0,updated=0,deleted=0,unchanged=0;const manual=existing.filter((element)=>!data(element).giraffleManagedKey),managed:CanvasElement[]=[];for(const item of desired){const old=current.get(item.id);if(!old){created++;managed.push(item);continue;}if(comparable(old)===comparable(item)){unchanged++;managed.push(old);continue;}updated++;managed.push({...item,version:Math.max(1,old.version)+1,versionNonce:old.versionNonce,updated:Date.now()});}for(const old of existing){if(!data(old).giraffleManagedKey||wanted.has(old.id)||old.isDeleted)continue;deleted++;managed.push({...old,isDeleted:true,version:Math.max(1,old.version)+1,updated:Date.now()});}const nodes=desired.filter((element)=>data(element).giraffleManagedKind==="node"&&data(element).giraffleManagedPart==="shape").length,edges=desired.filter((element)=>data(element).giraffleManagedKind==="edge"&&data(element).giraffleManagedPart==="line").length;return{elements:[...manual,...managed],created,updated,deleted,unchanged,managedNodes:nodes,managedEdges:edges};}

export function applyCanvasSpec(input:{canvasId:string;elements:readonly CanvasElement[];pages:readonly Page[];spec:CanvasSpec;mode:"merge"|"replace"}):CanvasApplyResult{const pages=new Map(input.pages.map((page)=>[page.id,page]));const graph=input.mode==="replace"?{nodes:new Map(),edges:new Map()} as Graph:graphFrom(input.elements);addSpec(graph,input.spec,pages);layoutGraph(graph,input.spec.layout??"grid");return reconcile(input.elements,compile(input.canvasId,graph));}
export function addCanvasNode(input:{canvasId:string;elements:readonly CanvasElement[];pages:readonly Page[];node:CanvasSpecNode}):CanvasApplyResult{const graph=graphFrom(input.elements);const bounds=[...graph.nodes.values()];const right=bounds.length?Math.max(...bounds.map((node)=>node.x+node.width))+gapX:40;addSpec(graph,{nodes:[{...input.node,x:input.node.x??right,y:input.node.y??40}]},new Map(input.pages.map((page)=>[page.id,page])));return reconcile(input.elements,compile(input.canvasId,graph));}
export function connectCanvasNodes(input:{canvasId:string;elements:readonly CanvasElement[];pages:readonly Page[];edge:CanvasSpecEdge}):CanvasApplyResult{const graph=graphFrom(input.elements);addSpec(graph,{nodes:[],edges:[input.edge]},new Map(input.pages.map((page)=>[page.id,page])));return reconcile(input.elements,compile(input.canvasId,graph));}
export function layoutCanvas(input:{canvasId:string;elements:readonly CanvasElement[];mode:Exclude<CanvasLayout,"preserve">}):CanvasApplyResult{const graph=graphFrom(input.elements);layoutGraph(graph,input.mode);return reconcile(input.elements,compile(input.canvasId,graph));}
