[package]
name = "giraffle"
version = "0.4.2"
description = "Giraffle desktop shell"
authors = ["Yahya Efe Kuruçay"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "giraffle_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-store = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
tokio = { version = "1", features = ["io-util", "process", "macros", "rt-multi-thread", "sync", "time"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
