import type { Page as PageModel,PagePriority } from "@giraffle/domain";
import { router } from "expo-router";
import { Pressable,ScrollView,StyleSheet,Text,View } from "react-native";
import { EditableText } from "@/components/ui/EditableText";
import { Button,EmptyState,Icon,Segment } from "@/components/ui/primitives";
import { useTheme } from "@/design/ThemeProvider";
import { radii,spacing,typography } from "@/design/tokens";
import { useApp } from "@/state/AppProvider";
const priorities:[PagePriority,string][]=[["do","Focus"],["schedule","Plan"],["delegate","Delegate"],["eliminate","Drop"]];
export function ChildPageViews({parent}: {parent:PageModel}){const{colors}=useTheme();const{snapshot,run}=useApp();const children=snapshot.pages.filter((page)=>page.parentId===parent.id&&!page.isArchived).sort((a,b)=>a.position.localeCompare(b.position));const categories=snapshot.categories.filter((category)=>category.parentId===parent.id).sort((a,b)=>a.position.localeCompare(b.position));
const add=(categoryId:string|null=null)=>void run(async(repository)=>{const id=await repository.createPage({parentId:parent.id});if(categoryId)await repository.updatePage(id,{categoryId});return id;}).then((id)=>router.push(`/pages/${id}`));
const moveToCategory=(pageId:string,categoryId:string|null)=>void run((repository)=>repository.updatePage(pageId,{categoryId}));
const renameCategory=(categoryId:string,title:string)=>void run((repository)=>repository.updateCategory(categoryId,{title}));
const deleteCategory=(categoryId:string)=>void run((repository)=>repository.deleteCategory(categoryId));
return <View style={[styles.root,{borderTopColor:colors.border}]}><View style={styles.head}><View style={{flex:1}}><Text style={[typography.title,{color:colors.text}]}>Inside</Text><Text style={[typography.caption,{color:colors.muted}]}>{children.length} direct {children.length===1?"page":"pages"}</Text></View><Segment values={["list","category","priority"] as const} value={parent.childView} onChange={(childView)=>void run((repository)=>repository.updatePage(parent.id,{childView}))}/><Button icon="add" accessibilityLabel="Add child page" onPress={()=>add()}/></View>{parent.childView==="list"?<List pages={children}/>:parent.childView==="category"?<Category pages={children} categories={categories} onAdd={add} onMove={moveToCategory} onRename={renameCategory} onDelete={deleteCategory} onCreateCategory={()=>void run((repository)=>repository.createCategory({parentId:parent.id}))}/>:<Priority pages={children}/>}</View>;}
function Row({page}:{page:PageModel}){const{colors}=useTheme();return <Pressable onPress={()=>router.push(`/pages/${page.id}`)} style={[styles.row,{borderBottomColor:colors.border}]}><Icon name="document-text-outline" size={17} color={colors.secondary}/><View style={{flex:1}}><Text numberOfLines={1} style={[typography.body,{color:colors.text}]}>{page.title}</Text><Text numberOfLines={1} style={[typography.caption,{color:colors.muted}]}>{page.scheduledAt?.replace("T"," · ")??"Page"}</Text></View><Icon name="chevron-forward" size={15} color={colors.faint}/></Pressable>;}
function List({pages}:{pages:PageModel[]}){return pages.length?<View>{pages.map((page)=><Row key={page.id} page={page}/>)}</View>:<EmptyState icon="documents-outline" title="Nothing inside" body="Add a page to start building this branch."/>;}
function Category({pages,categories,onAdd,onMove,onRename,onDelete,onCreateCategory}:{pages:PageModel[];categories:{id:string;title:string;color:string|null}[];onAdd(id:string|null):void;onMove(pageId:string,categoryId:string|null):void;onRename(id:string,title:string):void;onDelete(id:string):void;onCreateCategory():void}){const{colors}=useTheme();const lanes=[...categories,{id:"none",title:"Uncategorized",color:null}];return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.lanes}>{lanes.map((category)=>{const items=pages.filter((page)=>(page.categoryId??"none")===category.id);return <View key={category.id} style={[styles.lane,{borderTopColor:category.color??colors.accent}]}><View style={styles.laneHead}>{category.id==="none"?<Text style={[typography.label,{color:colors.text,flex:1}]}>{category.title}</Text>:<EditableText value={category.title} onSave={(title)=>onRename(category.id,title)} style={[typography.label,{color:colors.text,flex:1}]}/>}<Text style={[typography.caption,{color:colors.muted}]}>{items.length}</Text>{category.id!=="none"?<Button icon="trash-outline" tone="danger" accessibilityLabel={`Delete ${category.title}`} onPress={()=>onDelete(category.id)}/>:null}<Button icon="add" accessibilityLabel={`Add to ${category.title}`} onPress={()=>onAdd(category.id==="none"?null:category.id)}/></View>{items.map((page)=><View key={page.id}><Row page={page}/><Button label="Move" icon="swap-horizontal-outline" accessibilityLabel={`Move ${page.title} to next category`} onPress={()=>{const index=lanes.findIndex((lane)=>lane.id===category.id);const next=lanes[(index+1)%lanes.length];onMove(page.id,next?.id==="none"?null:next?.id??null);}}/></View>)}</View>;})}<View style={[styles.newLane,{borderColor:colors.border}]}><Button label="Category" icon="add" onPress={onCreateCategory}/></View></ScrollView>;}
function Priority({pages}:{pages:PageModel[]}){const{colors}=useTheme();return <View style={styles.grid}>{[...priorities,[null,"No priority"] as const].map(([id,title])=>{const items=pages.filter((page)=>page.priority===id);return <View key={title} style={[styles.group,{borderColor:colors.border}]}><Text style={[typography.label,{color:colors.text}]}>{title}</Text><Text style={[typography.caption,{color:colors.muted}]}>{items.length}</Text>{items.map((page)=><Row key={page.id} page={page}/>)}</View>;})}</View>;}
const styles=StyleSheet.create({root:{paddingTop:spacing.lg,borderTopWidth:StyleSheet.hairlineWidth,gap:spacing.md},head:{flexDirection:"row",alignItems:"center",gap:spacing.sm},row:{minHeight:54,flexDirection:"row",alignItems:"center",gap:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth},lanes:{gap:spacing.lg,paddingBottom:spacing.sm},lane:{width:280,borderTopWidth:2},laneHead:{minHeight:44,flexDirection:"row",alignItems:"center",gap:spacing.sm},newLane:{width:160,height:56,padding:spacing.xs,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.sm},grid:{flexDirection:"row",flexWrap:"wrap",gap:spacing.md},group:{flexBasis:"47%",flexGrow:1,minWidth:180,minHeight:130,padding:spacing.md,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.md}});
