import type { Page,PagePriority } from "@giraffle/domain";
import { useState } from "react";
import { Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Button,Segment } from "@/components/ui/primitives";
import { useTheme } from "@/design/ThemeProvider";
import { radii,spacing,typography } from "@/design/tokens";
import { useApp } from "@/state/AppProvider";
const priorityLabels={none:"None",do:"Focus",schedule:"Plan",delegate:"Delegate",eliminate:"Drop"} as const;type PriorityChoice=PagePriority|"none";
export function PagePlanningSheet({page,visible,onClose}:{page:Page;visible:boolean;onClose():void}){const{colors}=useTheme();const{snapshot,run}=useApp();const[stateId,setStateId]=useState(page.stateId);const[priority,setPriority]=useState<PriorityChoice>(page.priority??"none");const[scheduledAt,setScheduledAt]=useState(page.scheduledAt??"");const[duration,setDuration]=useState(page.durationMinutes===null?"":String(page.durationMinutes));const save=async()=>{const minutes=duration?Number(duration):null;if(minutes!==null&&(!Number.isInteger(minutes)||minutes<1||minutes>1440))return;await run((repository)=>repository.updatePage(page.id,{stateId,priority:priority==="none"?null:priority,scheduledAt:scheduledAt.trim()||null,durationMinutes:minutes}));onClose();};return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={[styles.scrim,{backgroundColor:colors.scrim}]} onPress={onClose}/><SafeAreaView edges={["bottom"]} style={[styles.sheet,{backgroundColor:colors.surfaceStrong}]}><View style={styles.head}><Text style={[typography.title,{color:colors.text,flex:1}]}>Page planning</Text><Button icon="close" accessibilityLabel="Close" onPress={onClose}/></View><ScrollView contentContainerStyle={{gap:spacing.md}}><View style={styles.field}><Text style={[typography.label,{color:colors.muted}]}>State</Text><View style={styles.wrap}>{snapshot.states.map((state)=><Button key={state.id} label={state.title} tone={stateId===state.id?"accent":"quiet"} onPress={()=>setStateId(state.id)}/>)}</View></View><View style={styles.field}><Text style={[typography.label,{color:colors.muted}]}>Priority</Text><Segment values={["none","do","schedule","delegate","eliminate"] as const} value={priority} onChange={setPriority} labelFor={(value)=>priorityLabels[value]}/></View><View style={styles.field}><Text style={[typography.label,{color:colors.muted}]}>Schedule</Text><TextInput value={scheduledAt} onChangeText={setScheduledAt} placeholder="YYYY-MM-DDTHH:mm" placeholderTextColor={colors.faint} style={[styles.input,typography.body,{color:colors.text,borderColor:colors.border}]}/></View><View style={styles.field}><Text style={[typography.label,{color:colors.muted}]}>Duration in minutes</Text><TextInput value={duration} onChangeText={(value)=>setDuration(value.replace(/\D/g,""))} keyboardType="number-pad" placeholder="30" placeholderTextColor={colors.faint} style={[styles.input,typography.body,{color:colors.text,borderColor:colors.border}]}/></View></ScrollView><View style={styles.actions}><Button label="Cancel" onPress={onClose}/><Button label="Save" tone="accent" onPress={()=>void save()}/></View></SafeAreaView></Modal>;}
const styles=StyleSheet.create({scrim:{position:"absolute",inset:0},sheet:{width:"100%",maxWidth:680,maxHeight:"84%",alignSelf:"center",marginTop:"auto",padding:spacing.lg,borderTopLeftRadius:radii.lg,borderTopRightRadius:radii.lg,gap:spacing.md},head:{flexDirection:"row",alignItems:"center",gap:spacing.sm},field:{gap:spacing.xs},wrap:{flexDirection:"row",flexWrap:"wrap",gap:spacing.xs},input:{minHeight:46,paddingHorizontal:spacing.md,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.sm},actions:{flexDirection:"row",justifyContent:"flex-end",gap:spacing.sm}});
