import type { PageStateFamily } from "@giraffle/domain";
import { useState } from "react";
import { Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { EditableText } from "@/components/ui/EditableText";
import { Button,Segment } from "@/components/ui/primitives";
import { useTheme } from "@/design/ThemeProvider";
import { radii,spacing,typography } from "@/design/tokens";
import { useApp } from "@/state/AppProvider";
const families=["forever","open","done"] as const;
export function StateManagerSheet({visible,onClose}:{visible:boolean;onClose():void}){const{colors}=useTheme();const{snapshot,run}=useApp();const[title,setTitle]=useState("");const[family,setFamily]=useState<PageStateFamily>("open");const create=async()=>{const value=title.trim();if(!value)return;await run((repository)=>repository.createState({title:value,family}));setTitle("");};return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={[styles.scrim,{backgroundColor:colors.scrim}]} onPress={onClose}/><SafeAreaView edges={["bottom"]} style={[styles.sheet,{backgroundColor:colors.surfaceStrong}]}><View style={styles.head}><View style={{flex:1}}><Text style={[typography.title,{color:colors.text}]}>Custom states</Text><Text style={[typography.caption,{color:colors.muted}]}>Names are yours; families keep planning behavior predictable.</Text></View><Button icon="close" accessibilityLabel="Close" onPress={onClose}/></View><View style={[styles.composer,{borderColor:colors.border}]}><TextInput value={title} onChangeText={setTitle} onSubmitEditing={()=>void create()} placeholder="New state name" placeholderTextColor={colors.faint} style={[typography.body,{color:colors.text,flex:1}]}/><Button label="Add" icon="add" tone="accent" disabled={!title.trim()} onPress={()=>void create()}/></View><Segment values={families} value={family} onChange={setFamily}/><ScrollView style={{maxHeight:420}}>{families.map((group)=><View key={group} style={{paddingTop:spacing.md}}><Text style={[typography.label,{color:colors.muted,textTransform:"capitalize"}]}>{group}</Text>{snapshot.states.filter((state)=>state.family===group).map((state)=><View key={state.id} style={[styles.row,{borderBottomColor:colors.border}]}><EditableText value={state.title} onSave={(next)=>void run((repository)=>repository.updateState(state.id,{title:next}))} style={[typography.body,{color:colors.text,flex:1}]}/>{state.isDefault?<Text style={[typography.caption,{color:colors.accent}]}>Default</Text>:<><Button label="Default" onPress={()=>void run((repository)=>repository.updateState(state.id,{isDefault:true}))}/><Button icon="trash-outline" tone="danger" accessibilityLabel={`Delete ${state.title}`} onPress={()=>void run((repository)=>repository.deleteState(state.id))}/></>}</View>)}</View>)}</ScrollView></SafeAreaView></Modal>;}
const styles=StyleSheet.create({scrim:{position:"absolute",inset:0},sheet:{width:"100%",maxWidth:680,maxHeight:"88%",alignSelf:"center",marginTop:"auto",padding:spacing.lg,borderTopLeftRadius:radii.lg,borderTopRightRadius:radii.lg,gap:spacing.md},head:{flexDirection:"row",alignItems:"flex-start",gap:spacing.sm},composer:{minHeight:48,paddingLeft:spacing.md,paddingRight:spacing.xs,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.sm,flexDirection:"row",alignItems:"center",gap:spacing.sm},row:{minHeight:54,flexDirection:"row",alignItems:"center",gap:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth}});
