import type { PageState,PageStateFamily } from "@giraffle/domain";
import { useState } from "react";
import { Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,useWindowDimensions,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { EditableText } from "@/components/ui/EditableText";
import { useConfirm } from "@/components/ui/ConfirmProvider";
import { Button,Icon,Segment,type IconName } from "@/components/ui/primitives";
import { useTheme } from "@/design/ThemeProvider";
import { radii,spacing,typography,WIDE_LAYOUT_MIN_WIDTH } from "@/design/tokens";
import { useApp } from "@/state/AppProvider";
const families=["forever","open","done"] as const;
/** A state without a glyph of its own reads as the shape its family wears everywhere else. */
const familyIcon:Record<PageStateFamily,IconName>={forever:"bookmark-outline",open:"ellipse-outline",done:"checkmark-circle-outline"};
/** One state per line: the name is edited where it sits, and the actions wait for the pointer. */
function StateRow({state,wide}:{state:PageState;wide:boolean}){const{colors}=useTheme();const{run}=useApp();const confirm=useConfirm();const[hovered,setHovered]=useState(false);const write=(patch:{title?:string;isDefault?:boolean})=>void run((repository)=>repository.updateState(state.id,patch)).catch(()=>undefined);const remove=()=>void confirm({title:`Delete ${state.title||"this state"}?`,body:"Pages in this state move to the default state of the same family.",confirmLabel:"Delete",tone:"danger"}).then((ok)=>{if(ok)void run((repository)=>repository.deleteState(state.id)).catch(()=>undefined);});return <View onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)} style={[styles.row,{backgroundColor:wide&&hovered?colors.hover:"transparent"}]}>{state.icon?<Text style={styles.glyph}>{state.icon}</Text>:<Icon name={familyIcon[state.family]} size={16} color={colors.faint}/>}<EditableText value={state.title} accessibilityLabel={`Rename ${state.title}`} onSave={(next)=>write({title:next})} style={[typography.body,{flex:1,color:colors.text}]}/><Text numberOfLines={1} style={[typography.caption,styles.family,{color:colors.faint}]}>{state.family}</Text>{state.isDefault?<Icon name="checkmark" size={15} color={colors.accent}/>:hovered||!wide?<><Button label="Default" accessibilityLabel={`Make ${state.title} the default ${state.family} state`} onPress={()=>write({isDefault:true})}/><Button icon="trash-outline" tone="danger" accessibilityLabel={`Delete ${state.title}`} onPress={remove}/></>:null}</View>}
export function StateManagerSheet({visible,onClose}:{visible:boolean;onClose():void}){const{colors}=useTheme();const{snapshot,run}=useApp();const{width}=useWindowDimensions();const wide=width>=WIDE_LAYOUT_MIN_WIDTH;const[title,setTitle]=useState("");const[family,setFamily]=useState<PageStateFamily>("open");const create=()=>{const value=title.trim();if(!value)return;void run((repository)=>repository.createState({title:value,family})).then(()=>setTitle(""),()=>undefined);};
const body=<>
  <View style={styles.head}><Text numberOfLines={1} style={[typography.label,styles.headTitle,{color:colors.faint}]}>States</Text><Button icon="close" accessibilityLabel="Close" onPress={onClose}/></View>
  <ScrollView style={styles.list}>{snapshot.states.length?snapshot.states.map((state)=><StateRow key={state.id} state={state} wide={wide}/>):<Text style={[typography.body,styles.empty,{color:colors.muted}]}>No states yet.</Text>}</ScrollView>
  <Text style={[typography.label,styles.sectionLabel,{color:colors.faint}]}>New state</Text>
  <Segment values={families} value={family} onChange={setFamily}/>
  <View style={styles.composer}><TextInput accessibilityLabel="New state name" value={title} onChangeText={setTitle} onSubmitEditing={create} placeholder={`Name this ${family} state`} placeholderTextColor={colors.faint} style={[typography.body,styles.input,{color:colors.text}]}/><Button label="Add" icon="add" tone="accent" disabled={!title.trim()} onPress={create}/></View>
</>;
return <Modal visible={visible} transparent animationType={wide?"fade":"slide"} onRequestClose={onClose}><Pressable accessibilityRole="button" accessibilityLabel="Close" style={[styles.scrim,{backgroundColor:wide?"transparent":colors.scrim}]} onPress={onClose}/>{wide?<View pointerEvents="box-none" style={styles.centre}><View style={[styles.panel,{backgroundColor:colors.surfaceStrong,borderColor:colors.border}]}>{body}</View></View>:<SafeAreaView edges={["bottom"]} style={[styles.sheet,{backgroundColor:colors.surfaceStrong}]}>{body}</SafeAreaView>}</Modal>;}
const styles=StyleSheet.create({scrim:{position:"absolute",inset:0},centre:{flex:1,alignItems:"center",justifyContent:"center",padding:spacing.lg},panel:{width:320,paddingVertical:spacing.xs,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.md},sheet:{marginTop:"auto",paddingTop:spacing.xs,paddingBottom:spacing.xs,borderTopLeftRadius:radii.sheet,borderTopRightRadius:radii.sheet},head:{height:32,paddingLeft:spacing.sm,paddingRight:spacing.xs,marginHorizontal:spacing.xs,flexDirection:"row",alignItems:"center",gap:spacing.sm},headTitle:{flex:1,textTransform:"uppercase",letterSpacing:.6},sectionLabel:{height:32,paddingHorizontal:spacing.sm,marginHorizontal:spacing.xs,textTransform:"uppercase",letterSpacing:.6,lineHeight:32},list:{maxHeight:320},row:{height:32,paddingHorizontal:spacing.sm,marginHorizontal:spacing.xs,borderRadius:radii.sm,flexDirection:"row",alignItems:"center",gap:spacing.sm},glyph:{fontSize:typography.body.fontSize},family:{textTransform:"capitalize"},empty:{paddingHorizontal:spacing.sm,marginHorizontal:spacing.xs,paddingVertical:spacing.xs},composer:{height:32,paddingRight:spacing.xs,marginHorizontal:spacing.xs,flexDirection:"row",alignItems:"center",gap:spacing.sm},input:{flex:1,minWidth:0,height:32,paddingHorizontal:spacing.sm}});
