import type { CanvasElement,Page } from "@giraffle/domain";
import { DEFAULT_STATE_IDS,EMPTY_DOCUMENT } from "@giraffle/domain";
import { describe,expect,it } from "vitest";
import { addCanvasNode,applyCanvasSpec,connectCanvasNodes,layoutCanvas } from "../index";
const page=(id:string,title:string):Page=>({id,title,icon:null,parentId:null,position:"a0",stateId:DEFAULT_STATE_IDS.forever,categoryId:null,priority:null,scheduledAt:null,durationMinutes:null,description:null,childView:"list",isPinned:false,isArchived:false,document:EMPTY_DOCUMENT,createdAt:1,updatedAt:1});
const manual:CanvasElement={id:"hand",type:"freedraw",version:1,versionNonce:2,isDeleted:false,x:0,y:0,width:10,height:10,points:[[0,0],[10,10]]};
describe("canvas compiler",()=>{
  it("produces valid managed nodes, labels, bound arrows, and page references",()=>{const result=applyCanvasSpec({canvasId:"canvas",elements:[manual],pages:[page("p1","Research")],mode:"merge",spec:{layout:"mindmap",nodes:[{key:"root",text:"Research",pageId:"p1",style:"primary"},{key:"note",text:"One useful idea",style:"note"}],edges:[{from:"root",to:"note",label:"contains"}]}});expect(result).toMatchObject({created:6,managedNodes:2,managedEdges:1});expect(result.elements).toContainEqual(manual);const shape=result.elements.find((element)=>element.customData?.girafflePageId==="p1");expect(shape).toMatchObject({type:"rectangle",version:1,isDeleted:false,link:"https://giraffle.local/page/p1"});const arrow=result.elements.find((element)=>element.type==="arrow");expect(arrow).toMatchObject({startArrowhead:null,endArrowhead:"arrow"});expect(arrow?.startBinding).toMatchObject({elementId:expect.any(String)});expect(arrow?.endBinding).toMatchObject({elementId:expect.any(String)});});
  it("is idempotent and increments versions only when managed content changes",()=>{const spec={layout:"grid" as const,nodes:[{key:"a",text:"Alpha"}],edges:[]};const first=applyCanvasSpec({canvasId:"c",elements:[],pages:[],spec,mode:"merge"});const second=applyCanvasSpec({canvasId:"c",elements:first.elements,pages:[],spec,mode:"merge"});expect(second).toMatchObject({created:0,updated:0,deleted:0});const changed=applyCanvasSpec({canvasId:"c",elements:second.elements,pages:[],mode:"merge",spec:{...spec,nodes:[{key:"a",text:"Alpha changed"}]}});expect(changed.updated).toBe(2);expect(changed.elements.filter((element)=>element.customData?.giraffleManagedKey==="a").every((element)=>element.version===2)).toBe(true);});
  it("supports incremental node, edge, and layout commands",()=>{const a=addCanvasNode({canvasId:"c",elements:[manual],pages:[],node:{key:"a",text:"Alpha"}});const b=addCanvasNode({canvasId:"c",elements:a.elements,pages:[],node:{key:"b",text:"Beta"}});const connected=connectCanvasNodes({canvasId:"c",elements:b.elements,pages:[],edge:{from:"a",to:"b",label:"next"}});const laidOut=layoutCanvas({canvasId:"c",elements:connected.elements,mode:"vertical"});expect(laidOut.managedNodes).toBe(2);expect(laidOut.managedEdges).toBe(1);expect(laidOut.elements.find((element)=>element.id==="hand")).toEqual(manual);});
  it("replace tombstones removed managed elements but leaves manual drawings",()=>{const first=applyCanvasSpec({canvasId:"c",elements:[manual],pages:[],mode:"merge",spec:{nodes:[{key:"a",text:"A"},{key:"b",text:"B"}],edges:[{from:"a",to:"b"}]}});const replaced=applyCanvasSpec({canvasId:"c",elements:first.elements,pages:[],mode:"replace",spec:{nodes:[{key:"a",text:"A"}],edges:[]}});expect(replaced.deleted).toBeGreaterThan(0);expect(replaced.elements.find((element)=>element.id==="hand")).toEqual(manual);expect(replaced.elements.some((element)=>element.customData?.giraffleManagedKey==="b"&&element.isDeleted)).toBe(true);});
});
