import{addDays,addMonths,dayKey,monthCells,parseDue,startOfWeek,type Page as PageModel}from"@giraffle/domain";import{router}from"expo-router";import{useMemo,useState}from"react";import{Pressable,StyleSheet,Text,useWindowDimensions,View}from"react-native";import{StateManagerSheet}from"@/components/pages/StateManagerSheet";import{ScreenTopbar}from"@/components/shell/ScreenTopbar";import{Page}from"@/components/ui/Page";import{Button,EmptyState,Icon,Segment}from"@/components/ui/primitives";import{useTheme}from"@/design/ThemeProvider";import{radii,spacing,typography,WIDE_LAYOUT_MIN_WIDTH}from"@/design/tokens";import{useApp}from"@/state/AppProvider";
type Lens="list"|"calendar"|"priority";const priorities=[{id:"do",title:"Focus",detail:"Do with attention"},{id:"schedule",title:"Plan",detail:"Give it time"},{id:"delegate",title:"Delegate",detail:"Waiting on someone"},{id:"eliminate",title:"Drop",detail:"Let it go"}]as const;
export default function Plan(){const{colors}=useTheme();const{snapshot,run}=useApp();const{width}=useWindowDimensions();const[lens,setLens]=useState<Lens>("list"),[day,setDay]=useState(()=>dayKey(new Date())),[statesOpen,setStatesOpen]=useState(false);
const{family,planned,open,today,overdue}=useMemo(()=>{const now=dayKey(new Date()),family=new Map(snapshot.states.map((state)=>[state.id,state.family])),planned=snapshot.pages.filter((page)=>!page.isArchived&&family.get(page.stateId)!=="forever"),open=planned.filter((page)=>family.get(page.stateId)==="open");return{family,planned,open,today:open.filter((page)=>parseDue(page.scheduledAt)?.day===now).length,overdue:open.filter((page)=>{const due=parseDue(page.scheduledAt)?.day;return due?due<now:false}).length};},[snapshot]);const toggle=(page:PageModel)=>{const next=family.get(page.stateId)==="done"?"open":"done",state=snapshot.states.find((item)=>item.family===next&&item.isDefault)??snapshot.states.find((item)=>item.family===next);if(state)void run((repository)=>repository.updatePage(page.id,{stateId:state.id}));};return <><ScreenTopbar title="Plan" action={<View style={styles.actions}><Button icon="options-outline" accessibilityLabel="Manage states" onPress={()=>setStatesOpen(true)}/><Button label="Capture" icon="flash-outline" tone="accent" onPress={()=>void run((repository)=>repository.createCapture("Untitled"))}/></View>}/><Page><View style={styles.intro}><View style={{flex:1}}><Text style={[typography.heading,{color:colors.text}]}>Personal planning</Text><Text style={[typography.body,{color:colors.muted}]}>Pages that ask for your attention.</Text></View><View style={styles.metrics}><Metric value={open.length} label="open"/><Metric value={today} label="today"/><Metric value={overdue} label="overdue" danger={overdue>0}/></View></View><Segment values={["list","calendar","priority"]as const} value={lens} onChange={setLens}/>{lens==="list"?<PageList pages={planned} family={family} onToggle={toggle}/>:lens==="priority"?<PriorityLens pages={open} compact={width<WIDE_LAYOUT_MIN_WIDTH}/>:<CalendarLens pages={planned} day={day} onDay={setDay} compact={width<WIDE_LAYOUT_MIN_WIDTH}/>}</Page><StateManagerSheet visible={statesOpen} onClose={()=>setStatesOpen(false)}/></>}
function Metric({value,label,danger}:{value:number;label:string;danger?:boolean}){const{colors}=useTheme();return <View style={styles.metric}><Text style={[styles.metricValue,{color:danger?colors.danger:colors.text}]}>{value}</Text><Text style={[typography.caption,{color:colors.muted}]}>{label}</Text></View>}
function PageList({pages,family,onToggle}:{pages:PageModel[];family:Map<string,string>;onToggle(page:PageModel):void}){const{colors}=useTheme();if(!pages.length)return <EmptyState icon="checkmark-circle-outline" title="Nothing asking for attention" body="Capture an idea or give any Page an open state."/>;return <View style={[styles.list,{borderTopColor:colors.border}]}>{[...pages].sort((a,b)=>(a.scheduledAt??"z").localeCompare(b.scheduledAt??"z")||b.updatedAt-a.updatedAt).map((page)=><View key={page.id} style={[styles.row,{borderBottomColor:colors.border}]}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:family.get(page.stateId)==="done"}} onPress={()=>onToggle(page)} style={[styles.check,{borderColor:family.get(page.stateId)==="done"?colors.accent:colors.borderStrong,backgroundColor:family.get(page.stateId)==="done"?colors.accent:"transparent"}]}>{family.get(page.stateId)==="done"?<Icon name="checkmark" size={13} color={colors.accentInk}/>:null}</Pressable><Pressable onPress={()=>router.push(`/pages/${page.id}`)} style={{flex:1,minWidth:0,gap:2}}><Text numberOfLines={1} style={[typography.body,{color:colors.text,fontWeight:"600",textDecorationLine:family.get(page.stateId)==="done"?"line-through":"none"}]}>{page.title}</Text><Text style={[typography.caption,{color:colors.muted}]}>{page.scheduledAt?.replace("T"," · ")??snapshotLabel(page)}{page.durationMinutes?` · ${page.durationMinutes}m`:""}</Text></Pressable>{page.priority?<Text style={[typography.caption,styles.priority,{color:colors.accent,backgroundColor:colors.accentSubtle}]}>{page.priority}</Text>:null}<Icon name="chevron-forward" size={15} color={colors.faint}/></View>)}</View>}
const snapshotLabel=(page:PageModel)=>page.description||"Unscheduled";
function PriorityLens({pages,compact}:{pages:PageModel[];compact:boolean}){const{colors}=useTheme();return <View style={[styles.priorityGrid,compact&&styles.priorityStack]}>{priorities.map((priority)=>{const items=pages.filter((page)=>page.priority===priority.id);return <View key={priority.id} style={[styles.group,{borderTopColor:colors.border}]}><View style={styles.groupHead}><View style={{flex:1}}><Text style={[typography.title,{color:colors.text}]}>{priority.title}</Text><Text style={[typography.caption,{color:colors.muted}]}>{priority.detail}</Text></View><Text style={[typography.caption,{color:colors.faint}]}>{items.length}</Text></View>{items.map((page)=><Pressable key={page.id} onPress={()=>router.push(`/pages/${page.id}`)} style={[styles.priorityRow,{borderTopColor:colors.border}]}><Text numberOfLines={2} style={[typography.body,{color:colors.secondary,flex:1}]}>{page.title}</Text><Icon name="arrow-forward" size={14} color={colors.faint}/></Pressable>)}{!items.length?<Text style={[typography.caption,{color:colors.faint,paddingVertical:spacing.lg}]}>Nothing here</Text>:null}</View>})}</View>}
type CalendarMode="day"|"week"|"month";const WEEKDAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const dayLabel=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});
const monthLabel=(day:string)=>new Date(`${day.slice(0,7)}-01T12:00:00`).toLocaleDateString(undefined,{month:"long",year:"numeric"});
const weekdayLabel=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString(undefined,{weekday:"short",day:"numeric"});
const weekLabel=(days:string[])=>{const first=days[0],last=days.at(-1);if(!first||!last)return"";const start=new Date(`${first}T12:00:00`),end=new Date(`${last}T12:00:00`);return `${start.toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${end.toLocaleDateString(undefined,{...(start.getMonth()===end.getMonth()?{}:{month:"short" as const}),day:"numeric"})}`;};
/** One schedule, three depths: a day to work in, a week to steer, a month to see shape. */
function CalendarLens({pages,day,onDay,compact}:{pages:PageModel[];day:string;onDay(value:string):void;compact:boolean}){const{colors}=useTheme();const{run}=useApp();const[mode,setMode]=useState<CalendarMode>("day");
const byDay=useMemo(()=>{const map=new Map<string,PageModel[]>();for(const page of pages){const due=parseDue(page.scheduledAt)?.day;if(!due)continue;const list=map.get(due);if(list)list.push(page);else map.set(due,[page]);}for(const list of map.values())list.sort((a,b)=>(a.scheduledAt??"").localeCompare(b.scheduledAt??""));return map;},[pages]);
const week=useMemo(()=>{const first=startOfWeek(day);return Array.from({length:7},(_,index)=>addDays(first,index));},[day]);
const cells=useMemo(()=>monthCells(day),[day]);
const today=dayKey(new Date()),items=byDay.get(day)??[];
const step=(direction:number)=>onDay(mode==="day"?addDays(day,direction):mode==="week"?addDays(day,direction*7):addMonths(day,direction));
const openDay=(value:string)=>{onDay(value);setMode("day");};
const schedule=async()=>{const id=await run((repository)=>repository.createScheduledPage({title:"Untitled",scheduledAt:day,durationMinutes:30}));router.push(`/pages/${id}`)};
return <View style={styles.calendar}><View style={styles.dayBar}><Button icon="chevron-back" accessibilityLabel={`Previous ${mode}`} onPress={()=>step(-1)}/><View style={{flex:1,alignItems:"center"}}><Text style={[typography.title,{color:colors.text}]}>{mode==="day"?dayLabel(day):mode==="week"?weekLabel(week):monthLabel(day)}</Text>{day!==today?<Pressable onPress={()=>onDay(today)}><Text style={[typography.caption,{color:colors.accent}]}>Return to today</Text></Pressable>:null}</View><Button icon="chevron-forward" accessibilityLabel={`Next ${mode}`} onPress={()=>step(1)}/></View><Segment values={["day","week","month"]as const} value={mode} onChange={setMode}/>
{mode==="day"?(items.length?items.map((page)=><Pressable key={page.id} onPress={()=>router.push(`/pages/${page.id}`)} style={[styles.calendarRow,{borderBottomColor:colors.border}]}><View style={[styles.calendarIcon,{backgroundColor:colors.accentSubtle}]}><Icon name="calendar-outline" color={colors.accent}/></View><Text style={[typography.body,{color:colors.text,flex:1,fontWeight:"600"}]}>{page.title}</Text><Text style={[typography.caption,{color:colors.muted}]}>{parseDue(page.scheduledAt)?.minutes===null?"All day":page.scheduledAt?.slice(11)}</Text></Pressable>):<EmptyState icon="calendar-clear-outline" title="A clear day" body="Leave it open or put one Page here." action={<Button label="Schedule a Page" icon="add" onPress={()=>void schedule()}/>}/>)
:mode==="week"?<View style={[styles.week,compact?styles.weekStack:null]}>{week.map((value)=>{const dayItems=byDay.get(value)??[];return <View key={value} style={[compact?styles.weekRow:styles.weekColumn,{borderTopColor:value===day?colors.accent:colors.border}]}><Pressable accessibilityRole="button" accessibilityLabel={`Open ${value}`} onPress={()=>openDay(value)} style={styles.weekHead}><Text numberOfLines={1} style={[typography.label,{color:value===today?colors.accent:colors.text}]}>{weekdayLabel(value)}</Text></Pressable>{dayItems.map((page)=><Pressable key={page.id} onPress={()=>router.push(`/pages/${page.id}`)} style={[styles.weekItem,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text numberOfLines={2} style={[typography.caption,{color:colors.text}]}>{page.title}</Text>{page.scheduledAt?.includes("T")?<Text style={[typography.caption,{color:colors.muted}]}>{page.scheduledAt.slice(11,16)}</Text>:null}</Pressable>)}</View>})}</View>
:<View style={styles.month}><View style={styles.monthWeekdays}>{WEEKDAYS.map((label)=><Text key={label} style={[typography.caption,styles.monthWeekday,{color:colors.faint}]}>{label}</Text>)}</View><View style={styles.monthGrid}>{cells.map((value)=>{const dayItems=byDay.get(value)??[];return <Pressable key={value} accessibilityRole="button" accessibilityLabel={`${value}, ${dayItems.length} scheduled`} onPress={()=>openDay(value)} style={[styles.monthCell,{borderColor:colors.border,backgroundColor:value===day?colors.accentSubtle:"transparent",opacity:value.slice(0,7)===day.slice(0,7)?1:0.42}]}><Text style={[typography.caption,{color:value===today?colors.accent:colors.text,fontWeight:value===today?"700":"400"}]}>{Number(value.slice(8,10))}</Text>{dayItems.slice(0,2).map((page)=><Text key={page.id} numberOfLines={1} style={[typography.caption,{color:colors.secondary}]}>{page.title}</Text>)}{dayItems.length>2?<Text style={[typography.caption,{color:colors.faint}]}>+{dayItems.length-2}</Text>:null}</Pressable>})}</View></View>}
</View>}
const styles=StyleSheet.create({actions:{flexDirection:"row",gap:spacing.xs},intro:{paddingBottom:spacing.lg,flexDirection:"row",alignItems:"flex-end",gap:spacing.xl},metrics:{flexDirection:"row",gap:spacing.xl},metric:{alignItems:"flex-end"},metricValue:{fontSize:24,lineHeight:27,fontWeight:"700",fontVariant:["tabular-nums"]},list:{borderTopWidth:StyleSheet.hairlineWidth},row:{minHeight:64,flexDirection:"row",alignItems:"center",gap:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth},check:{width:22,height:22,borderRadius:radii.full,borderWidth:1.5,alignItems:"center",justifyContent:"center"},priority:{paddingHorizontal:8,paddingVertical:3,borderRadius:radii.full,textTransform:"capitalize"},priorityGrid:{flexDirection:"row",flexWrap:"wrap",gap:spacing.xxl},priorityStack:{flexDirection:"column"},group:{flexBasis:"46%",flexGrow:1,minWidth:240,borderTopWidth:1,paddingTop:spacing.md},groupHead:{minHeight:52,flexDirection:"row",alignItems:"flex-start",gap:spacing.sm},priorityRow:{minHeight:48,paddingVertical:spacing.sm,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",gap:spacing.sm},calendar:{gap:spacing.md},dayBar:{minHeight:54,flexDirection:"row",alignItems:"center",gap:spacing.sm},calendarRow:{minHeight:62,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",gap:spacing.md},calendarIcon:{width:36,height:36,borderRadius:radii.sm,alignItems:"center",justifyContent:"center"},week:{flexDirection:"row",gap:spacing.xs},weekStack:{flexDirection:"column",gap:spacing.sm},weekColumn:{flex:1,minWidth:0,paddingTop:spacing.xs,borderTopWidth:2,gap:spacing.xs},weekRow:{paddingTop:spacing.xs,borderTopWidth:2,gap:spacing.xs},weekHead:{minHeight:30,flexDirection:"row",alignItems:"center",gap:spacing.xs},weekItem:{padding:spacing.xs,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.xs,gap:2},month:{gap:spacing.xs},monthWeekdays:{flexDirection:"row"},monthWeekday:{flexBasis:`${100/7}%`,textAlign:"center",textTransform:"uppercase",letterSpacing:.6},monthGrid:{flexDirection:"row",flexWrap:"wrap"},monthCell:{flexBasis:`${100/7}%`,minHeight:78,padding:4,borderWidth:StyleSheet.hairlineWidth,gap:1}});
