import{addDays,addMonths,dayKey,formatClock,groupPagesByDay,monthCells,parseDue,startOfWeek,type Page as PageModel,type PagePriority,type PageState}from"@giraffle/domain";import{router}from"expo-router";import{useMemo,useState,type ReactNode}from"react";import{Pressable,StyleSheet,Text,useWindowDimensions,View,type StyleProp,type ViewStyle}from"react-native";import{StateManagerSheet}from"@/components/pages/StateManagerSheet";import{ScreenTopbar}from"@/components/shell/ScreenTopbar";import{Page}from"@/components/ui/Page";import{Button,Icon,Segment}from"@/components/ui/primitives";import{useTheme}from"@/design/ThemeProvider";import{controls,radii,spacing,typography,WIDE_LAYOUT_MIN_WIDTH}from"@/design/tokens";import{useApp}from"@/state/AppProvider";
type Lens="table"|"board"|"calendar"|"list";const LENSES=["table","board","calendar","list"]as const;
const PRIORITIES:Record<PagePriority,string>={do:"Focus",schedule:"Plan",delegate:"Delegate",eliminate:"Drop"};
const titleOf=(page:PageModel)=>page.title||"Untitled";
/** Scheduled first and soonest at the top, then whatever moved most recently. */
const byPlan=(a:PageModel,b:PageModel)=>(a.scheduledAt??"z").localeCompare(b.scheduledAt??"z")||b.updatedAt-a.updatedAt;
const dateLabel=(scheduledAt:string|null)=>{const due=parseDue(scheduledAt);if(!due)return"";const label=new Date(`${due.day}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"});return due.minutes===null?label:`${label} ${formatClock(due.minutes)}`;};
const isLate=(page:PageModel,state:PageState|undefined,today:string)=>{const due=parseDue(page.scheduledAt)?.day;return state?.family==="open"&&due?due<today:false;};
/** Planning is one database of pages; a lens only changes the shape it is read in. */
export default function Plan(){const{snapshot,run}=useApp();const{width}=useWindowDimensions();const[lens,setLens]=useState<Lens>("table"),[day,setDay]=useState(()=>dayKey(new Date())),[statesOpen,setStatesOpen]=useState(false);const compact=width<WIDE_LAYOUT_MIN_WIDTH,today=dayKey(new Date());
const{states,stateById,pages}=useMemo(()=>{const stateById=new Map(snapshot.states.map((state)=>[state.id,state]));return{stateById,states:snapshot.states.filter((state)=>state.family!=="forever").sort((a,b)=>a.position.localeCompare(b.position)),pages:snapshot.pages.filter((page)=>!page.isArchived&&stateById.get(page.stateId)?.family!=="forever").sort(byPlan)};},[snapshot]);
const toggle=(page:PageModel)=>{const next=stateById.get(page.stateId)?.family==="done"?"open":"done",state=snapshot.states.find((item)=>item.family===next&&item.isDefault)??snapshot.states.find((item)=>item.family===next);if(state)void run((repository)=>repository.updatePage(page.id,{stateId:state.id}));};
return <><ScreenTopbar title="Plan" action={<View style={styles.actions}><Button icon="options-outline" accessibilityLabel="Manage states" onPress={()=>setStatesOpen(true)}/><Button label="Capture" icon="flash-outline" onPress={()=>void run((repository)=>repository.createCapture("Untitled"))}/></View>}/><Page wide><Segment values={LENSES} value={lens} onChange={setLens}/>{lens==="table"?<TableLens pages={pages} stateById={stateById} today={today} compact={compact} onToggle={toggle}/>:lens==="board"?<BoardLens states={states} pages={pages} compact={compact}/>:lens==="calendar"?<CalendarLens pages={pages} day={day} onDay={setDay} compact={compact}/>:<ListLens pages={pages} stateById={stateById} today={today}/>}</Page><StateManagerSheet visible={statesOpen} onClose={()=>setStatesOpen(false)}/></>}
/** Every way into a page carries the same navigation, label and hover. */
function PageLink({page,style,children}:{page:PageModel;style(active:boolean):StyleProp<ViewStyle>;children:ReactNode}){const[hovered,setHovered]=useState(false);return <Pressable accessibilityRole="link" accessibilityLabel={`Open ${titleOf(page)}`} onHoverIn={()=>setHovered(true)} onHoverOut={()=>setHovered(false)} onPress={()=>router.push(`/pages/${page.id}`)} style={({pressed})=>style(pressed||hovered)}>{children}</Pressable>}
function Quiet({text}:{text:string}){const{colors}=useTheme();return <Text style={[typography.caption,styles.quiet,{color:colors.faint}]}>{text}</Text>}
function TableLens({pages,stateById,today,compact,onToggle}:{pages:PageModel[];stateById:Map<string,PageState>;today:string;compact:boolean;onToggle(page:PageModel):void}){const{colors}=useTheme();
if(!pages.length)return <Quiet text="Nothing in play. Capture a page, or give one an open state."/>;
return <View><View style={[styles.row,styles.head,{borderBottomColor:colors.border}]}><Text style={[styles.column,styles.name,{color:colors.muted}]}>Name</Text><Text style={[styles.column,styles.state,{color:colors.muted}]}>State</Text>{compact?null:<Text style={[styles.column,styles.priority,{color:colors.muted}]}>Priority</Text>}<Text style={[styles.column,styles.date,{color:colors.muted}]}>Date</Text></View>
{pages.map((page)=>{const state=stateById.get(page.stateId),done=state?.family==="done";return <View key={page.id} style={[styles.row,styles.body,{borderBottomColor:colors.border}]}><PageLink page={page} style={(active)=>[styles.name,styles.nameLink,{backgroundColor:active?colors.hover:"transparent"}]}>{page.icon?<Text style={styles.glyph}>{page.icon}</Text>:<Icon name="document-text-outline" size={15} color={colors.faint}/>}<Text numberOfLines={1} style={[typography.body,{color:colors.text,flex:1,textDecorationLine:done?"line-through":"none"}]}>{titleOf(page)}</Text></PageLink><Pressable accessibilityRole="button" accessibilityState={{checked:done}} accessibilityLabel={`Move ${titleOf(page)} to ${done?"open":"done"}`} onPress={()=>onToggle(page)} style={styles.state}><Text numberOfLines={1} style={[typography.caption,styles.chip,{color:colors.secondary,backgroundColor:colors.surface}]}>{state?.title??"—"}</Text></Pressable>{compact?null:<Text numberOfLines={1} style={[typography.caption,styles.priority,{color:colors.muted}]}>{page.priority?PRIORITIES[page.priority]:""}</Text>}<Text numberOfLines={1} style={[typography.caption,styles.date,{color:isLate(page,state,today)?colors.danger:colors.muted}]}>{dateLabel(page.scheduledAt)}</Text></View>})}</View>}
/** Columns are the workspace's own states, so a board says what the vocabulary says. */
function BoardLens({states,pages,compact}:{states:PageState[];pages:PageModel[];compact:boolean}){const{colors}=useTheme();
if(!states.length)return <Quiet text="No states to group by yet."/>;
return <View style={[styles.board,compact?styles.stack:null]}>{states.map((state)=>{const items=pages.filter((page)=>page.stateId===state.id);return <View key={state.id} style={styles.lane}><View style={styles.laneHead}><Text numberOfLines={1} style={[typography.label,{color:colors.text}]}>{state.title}</Text><Text style={[typography.caption,{color:colors.faint}]}>{items.length}</Text></View>{items.map((page)=><PageLink key={page.id} page={page} style={(active)=>[styles.card,{borderColor:colors.border,backgroundColor:active?colors.hover:colors.surface}]}><Text numberOfLines={2} style={[typography.body,{color:colors.text}]}>{titleOf(page)}</Text>{page.scheduledAt?<Text style={[typography.caption,styles.chip,{color:colors.accent,backgroundColor:colors.accentSubtle}]}>{dateLabel(page.scheduledAt)}</Text>:null}</PageLink>)}{items.length?null:<Quiet text="Nothing here"/>}</View>})}</View>}
function ListLens({pages,stateById,today}:{pages:PageModel[];stateById:Map<string,PageState>;today:string}){const{colors}=useTheme();
if(!pages.length)return <Quiet text="Nothing in play. Capture a page, or give one an open state."/>;
return <View style={[styles.list,{borderTopColor:colors.border}]}>{pages.map((page)=>{const state=stateById.get(page.stateId);return <PageLink key={page.id} page={page} style={(active)=>[styles.listRow,{borderBottomColor:colors.border,backgroundColor:active?colors.hover:"transparent"}]}><View style={styles.listCopy}><Text numberOfLines={1} style={[typography.title,{color:colors.text}]}>{titleOf(page)}</Text><Text numberOfLines={1} style={[typography.caption,{color:colors.muted}]}>{page.description||state?.title||"No state"}</Text></View><Text style={[typography.caption,{color:isLate(page,state,today)?colors.danger:colors.muted}]}>{dateLabel(page.scheduledAt)}</Text></PageLink>})}</View>}
type CalendarMode="day"|"week"|"month";const WEEKDAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const dayLabel=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});
const monthLabel=(day:string)=>new Date(`${day.slice(0,7)}-01T12:00:00`).toLocaleDateString(undefined,{month:"long",year:"numeric"});
const weekdayName=(day:string)=>new Date(`${day}T12:00:00`).toLocaleDateString(undefined,{weekday:"short"});
const weekLabel=(days:string[])=>{const first=days[0],last=days.at(-1);if(!first||!last)return"";const start=new Date(`${first}T12:00:00`),end=new Date(`${last}T12:00:00`);return `${start.toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${end.toLocaleDateString(undefined,{...(start.getMonth()===end.getMonth()?{}:{month:"short" as const}),day:"numeric"})}`;};
/** A month cell is itself one pressable, so its chips are labels rather than links. */
function EventChip({page,clock}:{page:PageModel;clock:"always"|"time"|"none"}){const{colors}=useTheme();const due=parseDue(page.scheduledAt),time=due&&due.minutes!==null?formatClock(due.minutes):clock==="always"?"All day":null;
const body=<><Text numberOfLines={1} style={[typography.caption,{color:colors.text,flex:1}]}>{titleOf(page)}</Text>{clock!=="none"&&time?<Text style={[typography.caption,{color:colors.secondary}]}>{time}</Text>:null}</>;
if(clock==="none")return <View style={[styles.event,{backgroundColor:colors.accentSubtle}]}>{body}</View>;
return <PageLink page={page} style={(active)=>[styles.event,{backgroundColor:active?colors.hover:colors.accentSubtle}]}>{body}</PageLink>}
/** One schedule, three depths: a day to work in, a week to steer, a month to see shape. */
function CalendarLens({pages,day,onDay,compact}:{pages:PageModel[];day:string;onDay(value:string):void;compact:boolean}){const{colors}=useTheme();const{run}=useApp();const[mode,setMode]=useState<CalendarMode>("day");
const byDay=useMemo(()=>groupPagesByDay(pages),[pages]);
const week=useMemo(()=>{const first=startOfWeek(day);return Array.from({length:7},(_,index)=>addDays(first,index));},[day]);
const cells=useMemo(()=>monthCells(day),[day]);
const today=dayKey(new Date()),items=byDay.get(day)??[];
const step=(direction:number)=>onDay(mode==="day"?addDays(day,direction):mode==="week"?addDays(day,direction*7):addMonths(day,direction));
const openDay=(value:string)=>{onDay(value);setMode("day");};
const schedule=async()=>{const id=await run((repository)=>repository.createScheduledPage({title:"Untitled",scheduledAt:day,durationMinutes:30}));router.push(`/pages/${id}`)};
return <View style={styles.calendar}><View style={styles.dayBar}><Button icon="chevron-back" accessibilityLabel={`Previous ${mode}`} onPress={()=>step(-1)}/><View style={styles.dayTitle}><Text style={[typography.title,{color:colors.text}]}>{mode==="day"?dayLabel(day):mode==="week"?weekLabel(week):monthLabel(day)}</Text>{day!==today?<Pressable accessibilityRole="button" accessibilityLabel="Return to today" onPress={()=>onDay(today)}><Text style={[typography.caption,{color:colors.accent}]}>Today</Text></Pressable>:null}</View><Button icon="chevron-forward" accessibilityLabel={`Next ${mode}`} onPress={()=>step(1)}/><Button icon="add" accessibilityLabel={`Schedule a page on ${dayLabel(day)}`} onPress={()=>void schedule()}/></View><Segment values={["day","week","month"]as const} value={mode} onChange={setMode}/>
{mode==="day"?(items.length?<View style={styles.dayList}>{items.map((page)=><EventChip key={page.id} page={page} clock="always"/>)}</View>:<Quiet text="Nothing scheduled."/>)
:mode==="week"?<View style={[styles.week,compact?styles.stack:null]}>{week.map((value)=><View key={value} style={[compact?styles.weekRow:styles.weekColumn,{borderTopColor:value===day?colors.borderStrong:colors.border}]}><Pressable accessibilityRole="button" accessibilityLabel={`Open ${value}`} onPress={()=>openDay(value)} style={styles.weekHead}><Text style={[typography.caption,styles.weekday,{color:colors.muted}]}>{weekdayName(value)}</Text><Text style={[typography.title,{color:value===today?colors.accent:colors.text}]}>{Number(value.slice(8,10))}</Text></Pressable>{(byDay.get(value)??[]).map((page)=><EventChip key={page.id} page={page} clock="time"/>)}</View>)}</View>
:<View style={styles.month}><View style={styles.monthWeekdays}>{WEEKDAYS.map((label)=><Text key={label} style={[typography.caption,styles.monthWeekday,{color:colors.faint}]}>{label}</Text>)}</View><View style={styles.monthGrid}>{cells.map((value)=>{const dayItems=byDay.get(value)??[],inMonth=value.slice(0,7)===day.slice(0,7);return <Pressable key={value} accessibilityRole="button" accessibilityLabel={`${value}, ${dayItems.length} scheduled`} onPress={()=>openDay(value)} style={[styles.monthCell,{borderColor:colors.border,backgroundColor:value===day?colors.selected:"transparent"}]}><Text style={[typography.caption,{color:value===today?colors.accent:inMonth?colors.text:colors.faint,fontWeight:value===today?"700":"400"}]}>{Number(value.slice(8,10))}</Text>{dayItems.slice(0,2).map((page)=><EventChip key={page.id} page={page} clock="none"/>)}{dayItems.length>2?<Text style={[typography.caption,{color:colors.faint}]}>+{dayItems.length-2}</Text>:null}</Pressable>})}</View></View>}
</View>}
const styles=StyleSheet.create({actions:{flexDirection:"row",gap:spacing.xs},quiet:{paddingVertical:spacing.md},row:{flexDirection:"row",alignItems:"center",gap:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth},head:{minHeight:controls.compact},body:{minHeight:controls.default},column:{...typography.label,textTransform:"uppercase",letterSpacing:.6},name:{flex:1,minWidth:0},nameLink:{flexDirection:"row",alignItems:"center",gap:spacing.sm,minHeight:controls.compact,marginHorizontal:-spacing.xs,paddingHorizontal:spacing.xs,borderRadius:radii.sm},glyph:{width:19,textAlign:"center",fontSize:15},state:{width:112,justifyContent:"center"},priority:{width:96},date:{width:104,textAlign:"right"},chip:{alignSelf:"flex-start",paddingHorizontal:spacing.xs,paddingVertical:spacing.xxs,borderRadius:radii.xs,overflow:"hidden"},board:{flexDirection:"row",flexWrap:"wrap",gap:spacing.xl},stack:{flexDirection:"column"},lane:{flexBasis:"46%",flexGrow:1,minWidth:220,gap:spacing.xs},laneHead:{minHeight:controls.compact,flexDirection:"row",alignItems:"center",gap:spacing.sm},card:{padding:spacing.sm,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.md,gap:spacing.xs},list:{borderTopWidth:StyleSheet.hairlineWidth},listRow:{minHeight:52,flexDirection:"row",alignItems:"center",gap:spacing.md,marginHorizontal:-spacing.xs,paddingHorizontal:spacing.xs,borderBottomWidth:StyleSheet.hairlineWidth},listCopy:{flex:1,minWidth:0,gap:spacing.xxs},calendar:{gap:spacing.md},dayBar:{minHeight:controls.comfortable,flexDirection:"row",alignItems:"center",gap:spacing.sm},dayTitle:{flex:1,alignItems:"center"},dayList:{gap:spacing.xs},event:{flexDirection:"row",alignItems:"center",gap:spacing.xs,paddingHorizontal:spacing.xs,paddingVertical:spacing.xxs,borderRadius:radii.xs},week:{flexDirection:"row",gap:spacing.xs},weekColumn:{flex:1,minWidth:0,paddingTop:spacing.xs,borderTopWidth:1,gap:spacing.xxs},weekRow:{paddingTop:spacing.xs,borderTopWidth:1,gap:spacing.xxs},weekHead:{minHeight:controls.compact,flexDirection:"row",alignItems:"center",gap:spacing.xs},weekday:{textTransform:"uppercase",letterSpacing:.6},month:{gap:spacing.xs},monthWeekdays:{flexDirection:"row"},monthWeekday:{flexBasis:`${100/7}%`,textAlign:"center",textTransform:"uppercase",letterSpacing:.6},monthGrid:{flexDirection:"row",flexWrap:"wrap"},monthCell:{flexBasis:`${100/7}%`,minHeight:82,padding:spacing.xxs,borderWidth:StyleSheet.hairlineWidth,gap:spacing.xxs}});
