import { DEFAULT_STATE_IDS } from "@giraffle/domain";
import { enrollDevice,listDevices } from "@/infrastructure/sync/syncClient";
import { approveDevice } from "@/sync/deviceLink";
import { createClient,createVaultSecrets,SYNC_CONFIG,VAULT_ID,type TestClient } from "./support/client";
import { createRelay,type TestRelay } from "./support/relay";
import { resetTestDatabases } from "./support/sqlite";
let relay:TestRelay;
beforeEach(async()=>{resetTestDatabases();relay=await createRelay(VAULT_ID);global.fetch=relay.fetch;});
async function approve(first:TestClient,second:TestClient){await enrollDevice(SYNC_CONFIG,{vaultId:VAULT_ID,deviceId:first.deviceId,repository:first.repository});await enrollDevice(SYNC_CONFIG,{vaultId:VAULT_ID,deviceId:second.deviceId,repository:second.repository});const target=(await listDevices(SYNC_CONFIG,VAULT_ID)).find((device)=>device.deviceId===second.deviceId)!;await approveDevice(SYNC_CONFIG,{vaultId:VAULT_ID,repository:first.repository,target});}
describe("universal Page sync",()=>{
  it("converges recursive pages, custom states and categories",async()=>{const secrets=await createVaultSecrets();const first=await createClient({deviceId:"page-sync-a",secrets});const second=await createClient({deviceId:"page-sync-b",secrets});await approve(first,second);const projectId=await first.repository.createPage({title:"Giraffle"});const stateId=await first.repository.createState({title:"In progress",family:"open"});const categoryId=await first.repository.createCategory({parentId:projectId,title:"Now",stateIdOnEnter:stateId});const childId=await first.repository.createPage({title:"Ship release",parentId:projectId,stateId:DEFAULT_STATE_IDS.open});await first.repository.updatePage(childId,{categoryId,priority:"do"});await first.sync();await second.sync();const remote=await second.repository.snapshot();expect(remote.pages.find((page)=>page.id===childId)).toMatchObject({parentId:projectId,stateId,categoryId,priority:"do"});expect(remote.states.find((state)=>state.id===stateId)?.family).toBe("open");expect(remote.categories.find((category)=>category.id===categoryId)?.parentId).toBe(projectId);});
  it("converges independent concurrent page fields",async()=>{const secrets=await createVaultSecrets();const first=await createClient({deviceId:"field-sync-a",secrets});const second=await createClient({deviceId:"field-sync-b",secrets});await approve(first,second);const id=await first.repository.createPage({title:"Draft"});await first.sync();await second.sync();await first.repository.updatePage(id,{title:"Release"});await second.repository.updatePage(id,{priority:"schedule"});await first.sync();await second.sync();await first.sync();const left=(await first.repository.snapshot()).pages.find((page)=>page.id===id);const right=(await second.repository.snapshot()).pages.find((page)=>page.id===id);expect(left).toMatchObject({title:"Release",priority:"schedule"});expect(right).toMatchObject({title:"Release",priority:"schedule"});});
});
