import { DEFAULT_STATE_IDS } from "@giraffle/domain";
import { createClient,createVaultSecrets } from "./support/client";
import { resetTestDatabases } from "./support/sqlite";
beforeEach(()=>resetTestDatabases());
describe("universal recursive pages",()=>{
  it("captures an open child in Inbox and moves it to one real parent",async()=>{const client=await createClient({deviceId:"universal-page-device",secrets:await createVaultSecrets()});const captureId=await client.repository.createCapture("Ship release");let snapshot=await client.repository.snapshot();const inbox=snapshot.pages.find((page)=>page.title==="Inbox");expect(snapshot.pages.find((page)=>page.id===captureId)).toMatchObject({parentId:inbox?.id,stateId:DEFAULT_STATE_IDS.open});const projectId=await client.repository.createPage({title:"Giraffle"});await client.repository.movePage(captureId,projectId);snapshot=await client.repository.snapshot();expect(snapshot.pages.find((page)=>page.id===captureId)).toMatchObject({parentId:projectId,categoryId:null});});
  it("supports custom states and categories owned by one parent",async()=>{const client=await createClient({deviceId:"state-category-device",secrets:await createVaultSecrets()});const parentId=await client.repository.createPage({title:"Reading"});const waitingId=await client.repository.createState({title:"Waiting",family:"open"});const categoryId=await client.repository.createCategory({parentId,title:"Next",stateIdOnEnter:waitingId});const childId=await client.repository.createPage({title:"Systems book",parentId,stateId:DEFAULT_STATE_IDS.forever});await client.repository.updatePage(childId,{categoryId});const snapshot=await client.repository.snapshot();expect(snapshot.pages.find((page)=>page.id===childId)).toMatchObject({categoryId,stateId:waitingId});expect(snapshot.states.find((state)=>state.id===waitingId)?.family).toBe("open");});
  it("keeps archive independent from state",async()=>{const client=await createClient({deviceId:"archive-state-device",secrets:await createVaultSecrets()});const id=await client.repository.createPage({title:"Reference",stateId:DEFAULT_STATE_IDS.forever});await client.repository.archivePage(id);const archived=await client.database.getFirstAsync<{state_id:string;is_archived:number}>("SELECT state_id,is_archived FROM pages WHERE id=?",id);expect(archived).toEqual({state_id:DEFAULT_STATE_IDS.forever,is_archived:1});await client.repository.restorePage(id);expect((await client.repository.snapshot()).pages.find((page)=>page.id===id)).toMatchObject({stateId:DEFAULT_STATE_IDS.forever,isArchived:false});});
  it("keeps schedule metadata valid",async()=>{const client=await createClient({deviceId:"schedule-validation-device",secrets:await createVaultSecrets()});const id=await client.repository.createPage({title:"Deep work"});await expect(client.repository.updatePage(id,{scheduledAt:"2026-02-30T25:70"})).rejects.toThrow(/invalid calendar schedule/i);await expect(client.repository.updatePage(id,{durationMinutes:30})).rejects.toThrow(/duration requires/i);await expect(client.repository.updatePage(id,{calendarColor:"red"})).rejects.toThrow(/hex color/i);await client.repository.updatePage(id,{scheduledAt:"2026-08-05T09:30",durationMinutes:60,calendarColor:"#d60000"});await client.repository.updatePage(id,{scheduledAt:"2026-08-06"});expect((await client.repository.snapshot()).pages.find((page)=>page.id===id)).toMatchObject({scheduledAt:"2026-08-06",durationMinutes:null,calendarColor:"#d60000"});});
});
